version: '3.8'

services:
  # PostgreSQL adatbázis
  postgres:
    image: postgres:15-alpine
    container_name: haztartasi_postgres
    environment:
      POSTGRES_DB: haztartasi_app
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secure_password123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/backups:/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d haztartasi_app"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis cache és session store
  redis:
    image: redis:7-alpine
    container_name: haztartasi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # pgAdmin - adatbázis kezelő UI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: haztartasi_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@haztartasi.app
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: haztartasi_network
